const wordList = [
        { word: "cat", hint: "Meowing pet" },
        { word: "dog", hint: "Barking pet" },
        { word: "sun", hint: "Shines in the day" },
        { word: "moon", hint: "Glows at night" },
        { word: "book", hint: "Read stories in it" },
        { word: "tree", hint: "Has leaves" },
        { word: "fish", hint: "Swims in water" },
        { word: "bird", hint: "Flies in the sky" },
        { word: "house", hint: "People live here" },
        { word: "car", hint: "Drives on roads" },
        { word: "hat", hint: "Wear on head" },
        { word: "shoe", hint: "Wear on feet" },
        { word: "apple", hint: "Red or green or yellow fruit" },
        { word: "bed", hint: "Sleep here" },
        { word: "door", hint: "Open and close" },
        { word: "pen", hint: "Write with it" },
        { word: "key", hint: "Opens locks" },
        { word: "rain", hint: "Falls from sky" },
        { word: "snow", hint: "Cold and white" },
        { word: "baby", hint: "Little child" },
        { word: "hand", hint: "Has five fingers" },
        { word: "leg", hint: "Walk with it" },
        { word: "eye", hint: "See with it" },
        { word: "nose", hint: "Smell with it" },
        { word: "ear", hint: "Hear with it" },
        { word: "bus", hint: "Big car for many people" },
        { word: "flower", hint: "Grows in garden" },
        { word: "bread", hint: "Eat with butter" },
        { word: "water", hint: "Drink when thirsty" },
        { word: "clock", hint: "Tells time" },
        { word: "money", hint: "Buy things with it" },
        { word: "smile", hint: "Happy face" },
        { word: "grass", hint: "Green on ground" },
        { word: "king", hint: "Man with crown" },
        { word: "queen", hint: "Woman with crown" },
        { word: "song", hint: "Music with words" },
        { word: "ring", hint: "Wear on finger" },
        { word: "heart", hint: "Symbol of love" },
        { word: "light", hint: "Bright in dark" },
        { word: "dark", hint: "No light" },
        { word: "happy", hint: "Feeling good" },
        { word: "sad", hint: "Feeling bad" }
    ];